version: 2.1

orbs:
  maven: circleci/maven@0.0.12

parameters:
  app_src_directory: 
    default : '/AgilePPMTool/ppmtool'
    type: 'string'
    
workflows:
  maven_test:
    jobs:
      - maven/test:
          test_results_path: /test_results
